image: openjdk:latest

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle; chmod +x gradlew

cache:
  paths:
     - .gradle/

test:
  stage: test
  script:
    - ./gradlew check
  artifacts:
    paths:
      - build/reports/

pages:
  stage: deploy
  script:
    - ./gradlew dokkaHtml publishMavenPublicationToDav4jvmRepository
    - mkdir public && mv build/dokka public && mv build/repo public
  artifacts:
    paths:
      - public
  only:
    - master
